Repository mxrch/GHunt, pull requests merged in 2020-10, with the labels that each got.

#12 Update check_and_gen.py
  check_and_gen.py
  lib/gmaps.py
  lib/photos.py
Labels: enhancement

#40 update .gitignore for mac/linux usage
  .gitignore
Labels: enhancement, hacktoberfest-accepted

#8 Dockerize (fixes #7)
  .gitignore
  Dockerfile
  README.md
  check_and_gen.py
  config.py
  hunt.py
  lib/search.py
  resources/.gitkeep
Labels: enhancement

#57 big refactor, mainly for better readability
  check_and_gen.py
  config.py
  hunt.py
  lib/banner.py
  lib/gmaps.py
  lib/photos.py
  lib/search.py
  lib/utils.py
  lib/youtube.py
  requirements.txt
Labels: hacktoberfest-accepted
